### PR TITLE
Update README.md with URL to Cell Painting paper

### PR DESCRIPTION
**Pull request by shntnu**
This is mostly to test out the PR process discussed here 
https://github.com/cytomining/pycytominer/pull/136

### CODE REVIEW

**Comment by shntnu** [comment]
Oh wait – cytomining#136 isn't merged yet so I can't test it via this PR 🤦

**Comment by gwaybio** [comment]
oh, also @shntnu - it looks like you're trying to merge the "readme" branch into your own "master" branch, which you're totally free to do without any of the PR process guidelines!

**Comment by gwaybio** [comment]
but you are correct, the PULL_REQUEST_TEMPLATE and CODEOWNERS template won't trigger until we merge that other PR

**Comment by shntnu** [comment]
> which you're totally free to do without any of the PR process guidelines!

Haha! I'll try again when that PR is merged

**Comment by gwaybio** [comment]
alright https://github.com/cytomining/pycytominer/pull/136 is now merged!

**Pull request merged**
